services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: kickstarter-db
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - "3310:3306"
    volumes:
      - ./.srv/database:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: kickstarter-db
    ports:
      - "8000:80"
    volumes:
      - wordpress-core:/var/www/html
      - ./themes/:/var/www/html/wp-content/themes/
      - ./plugins/:/var/www/html/wp-content/plugins/
      - ./.srv/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - mysql
      

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_USERNAME: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
      PMA_HOST: mysql
    ports:
      - "8181:80"
    depends_on:
      - mysql

volumes:
  wordpress-core: